### Dataset Corrections

#### 1. Data Typing

In [13]:
import numpy as np
import pandas as pd

df = pd.read_csv('../data/02_interim/results_races_drivers_constructors.csv')
df

C:\Users\Patrick\AppData\Local\Temp\ipykernel_55492\3019245544.py:4: DtypeWarning: Columns (0: number_y) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/02_interim/results_races_drivers_constructors.csv')

,statusId,status,status_group,constructorId,constructorRef,name_x,nationality_x,url,driverId,driverRef,...,positionText,positionOrder,points,laps,time_y,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed
0,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,7,7,1.0,31,+1:00.733,4312825,17,11,1:39.141,201.276
1,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,6,6,3.0,56,+1:11.866,7135351,39,12,1:54.665,171.138
2,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,4,4,5.0,57,+22.096,5530278,13,6,1:34.915,205.269
3,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,13,13,0.0,58,+1:20.454,5265302,53,15,1:28.562,216.986
4,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,1,1,10.0,70,1:38:23.876,5903876,16,4,1:22.479,191.219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,140,Undertray,Others,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,849,latifi,...,R,19,0.0,48,\N,\N,14,19,1:10.890,219.280
26755,140,Undertray,Others,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari,844,leclerc,...,R,19,0.0,41,\N,\N,33,19,1:17.277,198.408
26756,140,Undertray,Others,117,aston_martin,Aston Martin,British,http://en.wikipedia.org/wiki/Aston_Martin_in_F...,4,alonso,...,R,16,0.0,49,\N,\N,47,7,1:39.954,198.559
26757,140,Undertray,Others,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,852,tsunoda,...,R,20,0.0,17,\N,\N,4,20,1:40.216,209.858
26758,141,Cooling system,Others,51,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,822,bottas,...,R,15,0.0,36,\N,\N,31,14,1:33.979,236.503

In [14]:
df_with_nan = df.replace(to_replace='\\N', value=np.nan)

df_with_nan

,statusId,status,status_group,constructorId,constructorRef,name_x,nationality_x,url,driverId,driverRef,...,positionText,positionOrder,points,laps,time_y,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed
0,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,7,7,1.0,31,+1:00.733,4312825,17,11,1:39.141,201.276
1,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,6,6,3.0,56,+1:11.866,7135351,39,12,1:54.665,171.138
2,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,4,4,5.0,57,+22.096,5530278,13,6,1:34.915,205.269
3,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,13,13,0.0,58,+1:20.454,5265302,53,15,1:28.562,216.986
4,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,1,1,10.0,70,1:38:23.876,5903876,16,4,1:22.479,191.219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,140,Undertray,Others,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,849,latifi,...,R,19,0.0,48,NaN,NaN,14,19,1:10.890,219.280
26755,140,Undertray,Others,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari,844,leclerc,...,R,19,0.0,41,NaN,NaN,33,19,1:17.277,198.408
26756,140,Undertray,Others,117,aston_martin,Aston Martin,British,http://en.wikipedia.org/wiki/Aston_Martin_in_F...,4,alonso,...,R,16,0.0,49,NaN,NaN,47,7,1:39.954,198.559
26757,140,Undertray,Others,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,852,tsunoda,...,R,20,0.0,17,NaN,NaN,4,20,1:40.216,209.858
26758,141,Cooling system,Others,51,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,822,bottas,...,R,15,0.0,36,NaN,NaN,31,14,1:33.979,236.503

Dropping columns where NaN is >= 90% of its values

In [30]:
df_size = len(df_with_nan)
print(f"Dataset Size: {df_size}")

drop_threshold = df_size * 0.90

df = df_with_nan.dropna(thresh=drop_threshold, axis="columns")
df

Dataset Size: 26759

,statusId,status,status_group,constructorId,constructorRef,name_x,nationality_x,url,driverId,driverRef,...,name_y,date,url_y,resultId,number_y,grid,positionText,positionOrder,points,laps
0,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,Malaysian Grand Prix,2009-04-05,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,7580,1,12,7,7,1.0,31
1,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,Chinese Grand Prix,2009-04-19,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,7599,1,9,6,6,3.0,56
2,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,Bahrain Grand Prix,2009-04-26,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,7617,1,5,4,4,5.0,57
3,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,Turkish Grand Prix,2009-06-07,http://en.wikipedia.org/wiki/2009_Turkish_Gran...,7686,1,16,13,13,0.0,58
4,1,Finished,Finished,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,hamilton,...,Hungarian Grand Prix,2009-07-26,http://en.wikipedia.org/wiki/2009_Hungarian_Gr...,7734,1,4,1,1,10.0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,140,Undertray,Others,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,849,latifi,...,Austrian Grand Prix,2022-07-10,http://en.wikipedia.org/wiki/2022_Austrian_Gra...,25624,6,17,R,19,0.0,48
26755,140,Undertray,Others,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari,844,leclerc,...,Dutch Grand Prix,2023-08-27,https://en.wikipedia.org/wiki/2023_Dutch_Grand...,26104,16,9,R,19,0.0,41
26756,140,Undertray,Others,117,aston_martin,Aston Martin,British,http://en.wikipedia.org/wiki/Aston_Martin_in_F...,4,alonso,...,United States Grand Prix,2023-10-22,https://en.wikipedia.org/wiki/2023_United_Stat...,26201,14,0,R,16,0.0,49
26757,140,Undertray,Others,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,852,tsunoda,...,French Grand Prix,2022-07-24,http://en.wikipedia.org/wiki/2022_French_Grand...,25645,22,8,R,20,0.0,17
26758,141,Cooling system,Others,51,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,822,bottas,...,Saudi Arabian Grand Prix,2022-03-27,http://en.wikipedia.org/wiki/2022_Saudi_Arabia...,25440,77,8,R,15,0.0,36

Fixing Object Column Types

In [45]:
df['date'] = pd.to_datetime(df['date'])

number_y = df['number_y']
number_y.loc[df['number_y'].isnull()] = 0

df['number_y'] = number_y
df['number_y'] = pd.to_numeric(df['number_y'])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   statusId        26759 non-null  int64
 1   status          26759 non-null  str
 2   status_group    26759 non-null  str
 3   constructorId   26759 non-null  int64
 4   constructorRef  26759 non-null  str
 5   name_x          26759 non-null  str
 6   nationality_x   26759 non-null  str
 7   url             26759 non-null  str
 8   driverId        26759 non-null  int64
 9   driverRef       26759 non-null  str
 10  forename        26759 non-null  str
 11  surname         26759 non-null  str
 12  dob             26759 non-null  str
 13  nationality_y   26759 non-null  str
 14  url_x           26759 non-null  str
 15  raceId          26759 non-null  int64
 16  year            26759 non-null  int64
 17  round           26759 non-null  int64
 18  circuitId       26759 non-null  int64
 19  name_y          26759 non-null  str
 20  date            26759 non-null  datetime64[us]
 21  url_y           26759 non-null  str
 22  resultId        26759 non-null  int64
 23  number_y        26759 non-null  int64
 24  grid            26759 non-null  int64
 25  positionText    26759 non-null  str
 26  positionOrder   26759 non-null  int64
 27  points          26759 non-null  float64
 28  laps            26759 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(12), str(15)
memory usage: 5.9 MB